name: publish release version

on:
  push:
    tags:
      - "v*"
  # 添加手动触发选项
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.6
          
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          cache: "pnpm"
          
      - run: pnpm install
      - run: pnpm build
      
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build

  create-release:
    needs: build
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: softprops/action-gh-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version || github.ref }}
          name: Release ${{ github.event.inputs.version || github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true

  upload-release:
    needs: [build, create-release]
    strategy:
      matrix:
        client: ["chrome", "edge", "firefox", "userscript"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build
          
      - name: Zip Release
        run: |
          cd build
          zip -r ${{ matrix.client }}.zip ${{ matrix.client }}
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version || github.ref }}
          files: build/${{ matrix.client }}.zip
          name: kiss-translator_${{ github.event.inputs.version || github.ref_name }}_${{ matrix.client }}.zip
